### ISSUE TITLE
Fails to compile on ZNC 1.6.3

### ISSUE THREAD

**Issue by Gerbyte** [wired/colloquypush#53]
znc-buildmod colloquy.cpp  
Building "colloquy.so" for ZNC 1.6.3... colloquy.cpp: In member function ‘bool CColloquyMod::Push(const CString&, const CString&, const CString&, bool, int)’:  
colloquy.cpp:778:58: error: invalid initialization of reference of type ‘std::vector<CClient*>&’ from expression of type ‘const std::vector<CClient*>’  
   vector<CClient*>& vpClients = GetNetwork()->GetClients();                                     25,381      Alles
                                                          ^
[ !! ] Error while building "colloquy.so"

**Comment by craigcabrey** [comment]
Change the line to read:

``` cpp
const vector<CClient*> vpClients = GetNetwork()->GetClients();
```

That allows me to compile, load, and use the module on ZNC v1.6.3.
