### ISSUE TITLE
Fails to compile with znc 1.5

### ISSUE THREAD

**Issue by fred0r** [wired/colloquypush#42]
Building module colloquy...
colloquy.cpp: In member function ‘bool CColloquyMod::Push(const CString&, const CString&, const CString&, bool, int)’:
colloquy.cpp:778:58: error: invalid initialization of reference of type ‘std::vector<CClient*>&’ from expression of type ‘const std::vector<CClient*>’
make[1]: **\* [colloquy.o] Fehler 1
make: **\* [modules] Fehler 2

:*(

**Comment by cbenard** [comment]
I have the same problem.

**Comment by cbenard** [comment]
@fred0r I fixed it by putting const before the vector declaration. The fixed line for ZNC 1.5 is:

`const vector<CClient*>& vpClients = GetNetwork()->GetClients();`

I was able to compile fine then.

**Comment by maxux** [comment]
Same for me, @cbenard fix works. Thanks.
