### ISSUE TITLE
Include paths not right and other issues

### ISSUE THREAD

**Issue by phistep** [wired/colloquypush#29]
Can't build the mod. My error log is here: http://pastie.org/4062083
As I get error messages like:

```
Building "colloquy.so" for ZNC 0.207...
colloquy.cpp:9:17: error: znc.h: No such file or directory
colloquy.cpp:10:18: error: Chan.h: No such file or directory
colloquy.cpp:11:18: error: User.h: No such file or directory
```

etc. I'd suppose it has something to do with me not having installed `znc` with root access and thus configured with `--prefix`. The header files above are now located in `~/znc/include/znc/` for me.

I tried to put the `colloquy.cpp` into the `modules` directory of the znc source tree as stated [here](http://wiki.znc.in/Compiling_modules) but this didn't help either. Maybe you just need to change the include paths.

So i changed the first `#includes` to

``` cpp
#include <znc/znc.h>
#include <znc/Chan.h>
#include <znc/User.h>
#include <znc/Modules.h>
#include <time.h>
```

and no I get way fewer errors:

```
Building module colloquy...
colloquy.cpp: In member function ‘virtual CModule::EModRet CColloquyMod::OnUserRaw(CString&)’:
colloquy.cpp:384: error: ‘class CUser’ has no member named ‘GetIRCServer’
colloquy.cpp:384: error: ‘class CUser’ has no member named ‘GetIRCNick’
colloquy.cpp: In member function ‘bool CColloquyMod::Push(const CString&, const CString&, const CString&, bool, int)’:
colloquy.cpp:716: error: ‘class CUser’ has no member named ‘IsIRCAway’
colloquy.cpp:763: error: ‘class CUser’ has no member named ‘GetClients’
colloquy.cpp:788: error: ‘class CUser’ has no member named ‘GetIRCNick’
```

And now I definitely have to give up. Building the file from tag 1.0 works though.

**Comment by lrusak** [comment]
I get this error also, I can't get it to work :(

**Comment by lrusak** [comment]
I was able to fix this by doing the following

my znc source code is located in my home directory.
I placed the colloquy.cpp in the modules folder within the znc source code.
I then ran the command /usr/local/bin/znc-buildmod /home/me/znc/modules/colloquy.cpp

It built successfully using the latest version (which you need for it to work with znc 0.206)

**Comment by duckydan** [comment]
Man, I can make this work. All kinds of errors on compiling. On Ubuntu 12.04.

**Comment by phistep** [comment]
@duckydan Well "All kinds of errors" is not really this useful. How about pasting the error log to something like [pastie](http://pastie.org) or [pastebin](http://pastebin.com)?

The OS is also not so helpful, better would be, if you told us which `g++` and which `znc` you were running.

Also have you tried to build [tag](https://github.com/wired/colloquypush/tags) 1.0? That worked for me.

**Comment by duckydan** [comment]
Sorry I was so vague. 1.0 worked perfectly to compile and load. After force-quitting the mobile apps, they requested the push permission and all is well. Thank you!

**Comment by phistep** [comment]
@wired Why have you closed the issue without attached commit? Has it been fixed?

**Comment by wired** [comment]
sorry, I misread the thread. So, you need the 1.0 tag for 0.207?

That just means that 0.207 (which was a development version? git?) has the 1.0 changes merged in, just use the 1.0 tag.
