### ISSUE TITLE
Fails to compile on 1.7

### ISSUE THREAD

**Issue by wcktklwn** [wired/colloquypush#47]
$ znc-buildmod colloquy.cpp
Building "colloquy.so" for ZNC 1.7.x... colloquy.cpp: In member function ‘bool CColloquyMod::Push(const CString&, const CString&, const CString&, bool, int)’:
colloquy.cpp:778:58: error: invalid initialization of reference of type ‘std::vector<CClient*>&’ from expression of type ‘const std::vector<CClient*>’
[ !! ] Error while building "colloquy.so"

**Comment by markus-lassfolk** [comment]
Check this one, it solved that issue for me on 1.6 

https://github.com/wired/colloquypush/commit/683d4360d112fad1a741136049e105fad86a5e32
