### ISSUE TITLE
Fails to compile on ZNC 1.6

### ISSUE THREAD

**Issue by teward** [wired/colloquypush#45]
THe following is the debug output: 

```
Building "colloquy.so" for ZNC 1.6.0... ./colloquy.cpp: In member function ‘bool CColloquyMod::Push(const CString&, const CString&, const CString&, bool, int)’:
./colloquy.cpp:778:58: error: invalid initialization of reference of type ‘std::vector<CClient*>&’ from expression of type ‘const std::vector<CClient*>’
[ !! ] Error while building "colloquy.so"
```

**Comment by teward** [comment]
This is fixed by Pull Request #46
